# Generated by Django 5.2.15 on 2026-07-29 13:38

import crowdfunding.utils
import django.db.models.deletion
import django_enum.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "withdrawal_reference",
                    models.CharField(
                        default=crowdfunding.utils.generate_withdrawal_reference,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("INR", "INR"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Approved", "APPROVED"),
                            ("Paid", "PAID"),
                            ("Rejected", "REJECTED"),
                            ("Failed", "FAILED"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "withdrawal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Donation", "DONATION"),
                            ("Refund", "REFUND"),
                            ("Withdrawal", "WITHDRAWAL"),
                            ("Deposit", "DEPOSIT"),
                            ("Campaign Promotion", "CAMPAIGN_PROMOTION"),
                        ],
                        max_length=18,
                    ),
                ),
                (
                    "gateway",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Razorpay", "RAZORPAY"),
                            ("Stripe", "STRIPE"),
                            ("Paypal", "PAYPAL"),
                            ("PayU", "PAYU"),
                            ("Cashfree", "CASHFREE"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_signature",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "payment_method",
                    django_enum.fields.EnumCharField(
                        blank=True,
                        choices=[
                            ("Card", "CARD"),
                            ("UPI", "UPI"),
                            ("Netbanking", "NETBANKING"),
                            ("Wallet", "WALLET"),
                            ("EMI", "EMI"),
                            ("Bank Transfer", "BANK_TRANSFER"),
                            ("Other", "OTHER"),
                        ],
                        max_length=13,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("INR", "INR"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Success", "SUCCESS"),
                            ("Failed", "FAILED"),
                            ("Refunded", "REFUNDED"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("refund_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("refund_reason", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="campaigns.campaignpromotionservice",
                    ),
                ),
                (
                    "donation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="donations.donation",
                    ),
                ),
                (
                    "withdrawal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.withdrawal",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="withdrawal",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ["INR", "USD", "EUR", "GBP"])),
                name="payments_Withdrawal_currency_Currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="withdrawal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["Pending", "Approved", "Paid", "Rejected", "Failed"],
                    )
                ),
                name="payments_Withdrawal_status_WithdrawalStatus",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "transaction_type__in",
                        [
                            "Donation",
                            "Refund",
                            "Withdrawal",
                            "Deposit",
                            "Campaign Promotion",
                        ],
                    )
                ),
                name="payments_PaymentTransaction_transaction_type_TransactionType",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "gateway__in",
                        ["Razorpay", "Stripe", "Paypal", "PayU", "Cashfree"],
                    )
                ),
                name="payments_PaymentTransaction_gateway_PaymentGateway",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "payment_method__in",
                        [
                            "Card",
                            "UPI",
                            "Netbanking",
                            "Wallet",
                            "EMI",
                            "Bank Transfer",
                            "Other",
                        ],
                    ),
                    ("payment_method__isnull", True),
                    _connector="OR",
                ),
                name="payments_PaymentTransaction_payment_method_PaymentMethod",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ["INR", "USD", "EUR", "GBP"])),
                name="payments_PaymentTransaction_currency_Currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["Pending", "Success", "Failed", "Refunded"])
                ),
                name="payments_PaymentTransaction_status_TransactionStatus",
            ),
        ),
    ]
