# Generated by Django 5.2.15 on 2026-08-06 13:33

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_remove_campaign_available_wallet_balance"),
        ("donations", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymenttransaction",
            name="payments_PaymentTransaction_gateway_PaymentGateway",
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="gateway",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Manual", "MANUAL"),
                    ("Razorpay", "RAZORPAY"),
                    ("Stripe", "STRIPE"),
                    ("Paypal", "PAYPAL"),
                    ("PayU", "PAYU"),
                    ("Cashfree", "CASHFREE"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "gateway__in",
                        ["Manual", "Razorpay", "Stripe", "Paypal", "PayU", "Cashfree"],
                    )
                ),
                name="payments_PaymentTransaction_gateway_PaymentGateway",
            ),
        ),
    ]
