# Generated by Django 5.2.15 on 2026-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_remove_paymenttransaction_payments_paymenttransaction_gateway_paymentgateway_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="gateway_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
