# Generated by Django 5.2.15 on 2026-08-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymenttransaction_gateway_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="gateway_reference_id",
        ),
    ]
