# Generated by Django 5.2.15 on 2026-08-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_remove_paymenttransaction_gateway_reference_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="gateway_fee",
        ),
    ]
