# Generated by Django 5.2.15 on 2026-08-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0029_alter_campaignpromotionservice_fee_and_more"),
        ("payments", "0005_remove_paymenttransaction_gateway_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="campaign_service",
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="campaign_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="payment_transactions",
                to="campaigns.campaignpromotionservice",
            ),
        ),
    ]
