# Generated by Django 5.2.15 on 2026-08-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_paymenttransaction_campaign_service_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymenttransaction",
            old_name="campaign_services",
            new_name="campaign_promotion_services",
        ),
    ]
