# Generated by Django 5.2.15 on 2026-08-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0007_rename_campaign_services_paymenttransaction_campaign_promotion_services",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="withdrawal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Withdrawal",
                "verbose_name_plural": "Withdrawals",
            },
        ),
    ]
