# Generated by Django 5.2.15 on 2026-09-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0035_alter_campaign_beneficiary_mobile"),
        ("donations", "0015_alter_donation_campaign_alter_donation_donor"),
        ("payments", "0008_alter_paymenttransaction_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="campaign_promotion_services",
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="donation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction",
                to="donations.donation",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="withdrawal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="payments.withdrawal",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawals",
                to="campaigns.campaign",
            ),
        ),
        migrations.CreateModel(
            name="PromotionServicePaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.paymenttransaction",
                    ),
                ),
                (
                    "promotion_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.campaignpromotionservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Service Payment Transaction",
                "verbose_name_plural": "Promotion Service Payment Transactions",
                "db_table": "promotion_service_payment_transaction",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment_transaction", "promotion_service"),
                        name="unique_payment_transaction_promotion_service",
                    )
                ],
            },
        ),
    ]
