# Generated by Django 5.2.15 on 2026-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0009_remove_paymenttransaction_campaign_promotion_services_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="gateway_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
