# Generated by Django 5.2.15 on 2026-09-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_paymenttransaction_gateway_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="gateway_fee",
        ),
    ]
