# Generated by Django 5.2.15 on 2026-09-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0038_alter_campaignpromotionservice_service_type_and_more"),
        ("payments", "0011_remove_paymenttransaction_gateway_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionservicepaymenttransaction",
            name="payment_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion_links",
                to="payments.paymenttransaction",
            ),
        ),
        migrations.AlterField(
            model_name="promotionservicepaymenttransaction",
            name="promotion_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_links",
                to="campaigns.campaignpromotionservice",
            ),
        ),
    ]
