# Generated by Django 5.2.15 on 2026-07-29 13:39

import django.db.models.deletion
import django_enum.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "applies_to",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Donor", "DONOR"),
                            ("Individual Fundraiser", "INDIVIDUAL_FUNDRAISER"),
                            ("NGO", "NGO"),
                            ("CSR", "CSR"),
                            ("Campaign", "CAMPAIGN"),
                            ("CSR Campaign", "CSR_CAMPAIGN"),
                        ],
                        max_length=21,
                    ),
                ),
            ],
            options={
                "db_table": "document_type",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "applies_to"),
                        name="unique_document_type_per_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "applies_to__in",
                                [
                                    "Donor",
                                    "Individual Fundraiser",
                                    "NGO",
                                    "CSR",
                                    "Campaign",
                                    "CSR Campaign",
                                ],
                            )
                        ),
                        name="verification_DocumentType_applies_to_DocOwner",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Profile Verification", "PROFILE_VERIFICATION"),
                            ("Campaign Verification", "CAMPAIGN_VERIFICATION"),
                            ("Bank Verification", "BANK_VERIFICATION"),
                        ],
                        max_length=21,
                    ),
                ),
                ("document_holder_name", models.CharField(max_length=255)),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("file_url", models.FileField(upload_to="documents/docs/%Y/%m/")),
                (
                    "verification_status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Approved", "APPROVED"),
                            ("Rejected", "REJECTED"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                (
                    "ai_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("verification_remarks", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="verification.documenttype",
                    ),
                ),
            ],
            options={
                "db_table": "document",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "document_type", "purpose"),
                        name="unique_user_document_type",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("campaign__isnull", False)),
                        fields=("campaign", "document_type", "purpose"),
                        name="unique_campaign_document_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "purpose__in",
                                [
                                    "Profile Verification",
                                    "Campaign Verification",
                                    "Bank Verification",
                                ],
                            )
                        ),
                        name="verification_Document_purpose_DocumentPurpose",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "verification_status__in",
                                ["Pending", "Approved", "Rejected"],
                            )
                        ),
                        name="verification_Document_verification_status_VerificationStatus",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityVerificationRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verification_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Donor", "DONOR"),
                            ("Individual Fundraiser", "INDIVIDUAL_FUNDRAISER"),
                            ("NGO", "NGO"),
                            ("CSR", "CSR"),
                            ("Campaign", "CAMPAIGN"),
                        ],
                        max_length=21,
                    ),
                ),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Approved", "APPROVED"),
                            ("Rejected", "REJECTED"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                (
                    "ai_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ai_result", models.JSONField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "entity_verification_requests",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "Pending")),
                        fields=("user",),
                        name="unique_pending_verification",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "verification_type__in",
                                [
                                    "Donor",
                                    "Individual Fundraiser",
                                    "NGO",
                                    "CSR",
                                    "Campaign",
                                ],
                            )
                        ),
                        name="ion_EntityVerificationRequest_verification_type_VerificationType",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["Pending", "Approved", "Rejected"])
                        ),
                        name="verification_EntityVerificationRequest_status_VerificationStatus",
                    ),
                ],
            },
        ),
    ]
