# Generated by Django 5.2.15 on 2026-08-01 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaign_is_deleted"),
        ("verification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entityverificationrequest",
            name="unique_pending_verification",
        ),
        migrations.AddConstraint(
            model_name="entityverificationrequest",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_verification_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityverificationrequest",
            constraint=models.UniqueConstraint(
                fields=("campaign",), name="unique_verification_per_campaign"
            ),
        ),
    ]
