# Generated by Django 5.2.15 on 2026-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0002_remove_entityverificationrequest_unique_pending_verification_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
    ]
