# Generated by Django 5.2.15 on 2026-08-06 04:31

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0007_remove_campaign_campaigns_campaign_beneficiary_group_type_beneficiarygrouptype_and_more",
        ),
        ("verification", "0003_documenttype_is_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="verification_Document_verification_status_VerificationStatus",
        ),
        migrations.RemoveConstraint(
            model_name="entityverificationrequest",
            name="verification_EntityVerificationRequest_status_VerificationStatus",
        ),
        migrations.AlterField(
            model_name="document",
            name="verification_status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Under Review", "UNDER_REVIEW"),
                    ("Rejected", "REJECTED"),
                ],
                default="Pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="entityverificationrequest",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Under Review", "UNDER_REVIEW"),
                    ("Rejected", "REJECTED"),
                ],
                default="Pending",
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_status__in",
                        ["Pending", "Approved", "Under Review", "Rejected"],
                    )
                ),
                name="verification_Document_verification_status_VerificationStatus",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityverificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["Pending", "Approved", "Under Review", "Rejected"])
                ),
                name="verification_EntityVerificationRequest_status_VerificationStatus",
            ),
        ),
    ]
