# Generated by Django 5.2.15 on 2026-08-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0004_remove_document_verification_document_verification_status_verificationstatus_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Type",
            },
        ),
        migrations.AlterModelOptions(
            name="entityverificationrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Verification Requests",
                "verbose_name_plural": "Verification Requests",
            },
        ),
        migrations.AlterModelTable(
            name="entityverificationrequest",
            table="verification_requests",
        ),
    ]
