# Generated by Django 5.2.15 on 2026-09-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0005_alter_document_options_alter_documenttype_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="DocumentType",
        ),
    ]
