# Generated by Django 5.2.15 on 2026-09-08 06:43

import crowdfunding.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0006_alter_document_document_type_delete_documenttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_url",
            field=models.FileField(
                upload_to=crowdfunding.upload_paths.document_upload_path
            ),
        ),
    ]
