# Generated by Django 5.2.15 on 2026-09-08 12:10

import crowdfunding.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0007_alter_document_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_url",
            field=models.FileField(
                max_length=500, upload_to=crowdfunding.upload_paths.document_upload_path
            ),
        ),
    ]
