# Generated by Django 5.2.15 on 2026-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0009_alter_document_campaign_alter_document_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_number",
            field=models.CharField(max_length=100),
        ),
    ]
