# Generated by Django 5.2.15 on 2026-09-23 16:28

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0041_alter_campaign_beneficiary_age"),
        ("verification", "0010_alter_document_document_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="verification_Document_verification_status_VerificationStatus",
        ),
        migrations.RemoveConstraint(
            model_name="entityverificationrequest",
            name="verification_EntityVerificationRequest_status_VerificationStatus",
        ),
        migrations.AlterField(
            model_name="document",
            name="verification_status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Rejected", "REJECTED"),
                ],
                default="Pending",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="entityverificationrequest",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Rejected", "REJECTED"),
                ],
                default="Pending",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verification_status__in", ["Pending", "Approved", "Rejected"])
                ),
                name="verification_Document_verification_status_VerificationStatus",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityverificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["Pending", "Approved", "Rejected"])),
                name="verification_EntityVerificationRequest_status_VerificationStatus",
            ),
        ),
    ]
