# Generated by Django 5.2.15 on 2026-09-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0011_remove_document_verification_document_verification_status_verificationstatus_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="document_holder_name",
        ),
        migrations.AlterField(
            model_name="document",
            name="document_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
