# Generated by Django 5.2.15 on 2026-07-29 13:38

import django.db.models.deletion
import django_enum.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSRProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("csr_name", models.CharField(max_length=255)),
                ("csr_reg_num", models.CharField(max_length=100, unique=True)),
                ("contact_person_name", models.CharField(max_length=255)),
                ("contact_person_designation", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csr_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "csr_profile",
            },
        ),
        migrations.CreateModel(
            name="NGOProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ngo_name", models.CharField(max_length=255)),
                (
                    "ngo_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Trust", "TRUST"),
                            ("Society", "SOCIETY"),
                            ("Section 8", "SECTION_8"),
                        ],
                        max_length=9,
                    ),
                ),
                ("reg_num", models.CharField(max_length=100, unique=True)),
                ("contact_person_name", models.CharField(max_length=255)),
                ("contact_person_designation", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NGO Profile",
                "verbose_name_plural": "NGO Profiles",
                "db_table": "ngo_profile",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ngo_type__in", ["Trust", "Society", "Section 8"])
                        ),
                        name="organizations_NGOProfile_ngo_type_NGOType",
                    )
                ],
            },
        ),
    ]
