# Generated by Django 5.2.15 on 2026-08-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csrprofile",
            options={
                "verbose_name": "CSR Profile",
                "verbose_name_plural": "CSR Profiles",
            },
        ),
    ]
