# Generated by Django 5.2.15 on 2026-09-23 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_ngoprofile_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csrprofile",
            name="pincode",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Pincode must be exactly 6 digits.", regex="^\\d{6}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="pincode",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Pincode must be exactly 6 digits.", regex="^\\d{6}$"
                    )
                ],
            ),
        ),
    ]
