# Generated by Django 5.2.15 on 2026-07-29 13:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "Only digits are allowed."
                            ),
                            django.core.validators.MinLengthValidator(10),
                        ],
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "otp",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "Only digits are allowed."
                            ),
                            django.core.validators.MinLengthValidator(10),
                        ],
                    ),
                ),
                ("is_mobile_verified", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/profile/%Y/%m/"
                    ),
                ),
                (
                    "user_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Individual Fundraiser", "INDIVIDUAL_FUNDRAISER"),
                            ("NGO", "NGO"),
                            ("CSR", "CSR"),
                            ("Admin", "ADMIN"),
                            ("Super Admin", "SUPER_ADMIN"),
                            ("Donor", "DONOR"),
                        ],
                        default="Donor",
                        max_length=21,
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Active", "ACTIVE"),
                            ("Suspended", "SUSPENDED"),
                            ("Deleted", "DELETED"),
                        ],
                        default="Active",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Basic Info", "BASIC_INFO"),
                            ("Profile Completed", "PROFILE_COMPLETED"),
                            ("Verification Pending", "VERIFICATION_PENDING"),
                            ("Verified", "VERIFIED"),
                            ("Verification Rejected", "VERIFICATION_REJECTED"),
                        ],
                        default="Basic Info",
                        max_length=21,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_holder_name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "account_number",
                    models.CharField(
                        max_length=18,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Account number must contain only digits and be between 9 and 18 digits long.",
                                regex="^\\d{9,18}$",
                            )
                        ],
                    ),
                ),
                (
                    "ifsc_code",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid IFSC code (e.g. SBIN0001234).",
                                regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                            )
                        ],
                    ),
                ),
                ("branch_name", models.CharField(max_length=255, null=True)),
                (
                    "cancelled_cheque",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/bank/cancelled-cheques/%Y/%m/",
                    ),
                ),
                (
                    "verification_status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Approved", "APPROVED"),
                            ("Rejected", "REJECTED"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_account",
            },
        ),
        migrations.CreateModel(
            name="DonorProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "donor_profile",
            },
        ),
        migrations.CreateModel(
            name="IndividualProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "individual_fundraiser_profile",
            },
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "user_type__in",
                        [
                            "Individual Fundraiser",
                            "NGO",
                            "CSR",
                            "Admin",
                            "Super Admin",
                            "Donor",
                        ],
                    )
                ),
                name="accounts_CustomUser_user_type_UserType",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["Active", "Suspended", "Deleted"])),
                name="accounts_CustomUser_status_Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "profile_status__in",
                        [
                            "Basic Info",
                            "Profile Completed",
                            "Verification Pending",
                            "Verified",
                            "Verification Rejected",
                        ],
                    )
                ),
                name="accounts_CustomUser_profile_status_ProfileStatus",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verification_status__in", ["Pending", "Approved", "Rejected"])
                ),
                name="accounts_BankAccount_verification_status_VerificationStatus",
            ),
        ),
    ]
