# Generated by Django 5.2.15 on 2026-07-29 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="mobile",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Only digits are allowed."
                    ),
                    django.core.validators.MinLengthValidator(10),
                ],
            ),
        ),
    ]
