# Generated by Django 5.2.15 on 2026-08-04 07:08

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_otp_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_type",
            field=django_enum.fields.EnumCharField(
                choices=[("Savings", "SAVINGS"), ("Current", "CURRENT")],
                default="Savings",
                max_length=7,
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("account_type__in", ["Savings", "Current"])),
                name="accounts_BankAccount_account_type_AccountType",
            ),
        ),
    ]
