# Generated by Django 5.2.15 on 2026-08-06 04:31

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_bankaccount_account_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bankaccount",
            name="accounts_BankAccount_verification_status_VerificationStatus",
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="verification_status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Under Review", "UNDER_REVIEW"),
                    ("Rejected", "REJECTED"),
                ],
                default="Pending",
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_status__in",
                        ["Pending", "Approved", "Under Review", "Rejected"],
                    )
                ),
                name="accounts_BankAccount_verification_status_VerificationStatus",
            ),
        ),
    ]
