# Generated by Django 5.2.15 on 2026-08-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_remove_bankaccount_accounts_bankaccount_verification_status_verificationstatus_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "User"},
        ),
        migrations.AlterModelOptions(
            name="donorprofile",
            options={
                "verbose_name": "Donor Profile",
                "verbose_name_plural": "Donor Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="individualprofile",
            options={
                "verbose_name": "Indivdual Fundraiser Profile",
                "verbose_name_plural": "Individual Fundraiser Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="otp",
            options={"verbose_name": "OTP", "verbose_name_plural": "OTP"},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="User",
        ),
    ]
