# Generated by Django 5.2.15 on 2026-08-24 07:35

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_alter_bankaccount_options_alter_customuser_options_and_more",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customuser",
            name="accounts_CustomUser_user_type_UserType",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Individual Fundraiser", "INDIVIDUAL_FUNDRAISER"),
                    ("NGO", "NGO"),
                    ("CSR", "CSR"),
                    ("Admin", "ADMIN"),
                    ("Super Admin", "SUPER_ADMIN"),
                    ("Donor", "DONOR"),
                    ("Platform Owner", "PLATFORM_OWNER"),
                ],
                default="Donor",
                max_length=21,
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "user_type__in",
                        [
                            "Individual Fundraiser",
                            "NGO",
                            "CSR",
                            "Admin",
                            "Super Admin",
                            "Donor",
                            "Platform Owner",
                        ],
                    )
                ),
                name="accounts_CustomUser_user_type_UserType",
            ),
        ),
    ]
