# Generated by Django 5.2.15 on 2026-09-08 12:11

import crowdfunding.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_bankaccount_cancelled_cheque_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="cancelled_cheque",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=crowdfunding.upload_paths.cancelled_cheque_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=crowdfunding.upload_paths.profile_picture_upload_path,
            ),
        ),
    ]
