# Generated by Django 5.2.15 on 2026-09-08 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_bankaccount_cancelled_cheque_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="verified_bank_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
