# Generated by Django 5.2.15 on 2026-09-23 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_bankaccount_verified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorprofile",
            name="pincode",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Pincode must contain only digits and be at most 6 digits.",
                        regex="^\\d{1,6}$",
                    )
                ],
            ),
        ),
    ]
