# Generated by Django 5.2.15 on 2026-09-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_donorprofile_pincode_and_more"),
        ("campaigns", "0041_alter_campaign_beneficiary_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="campaign",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficiary_bank_account",
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("campaign__isnull", True), ("user__isnull", False)),
                    models.Q(("campaign__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="bank_account_exactly_one_owner",
            ),
        ),
    ]
