# Generated by Django 5.2.15 on 2026-09-23 16:28

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_bankaccount_campaign_alter_bankaccount_user_and_more"),
        ("campaigns", "0041_alter_campaign_beneficiary_age"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bankaccount",
            name="accounts_BankAccount_verification_status_VerificationStatus",
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="verification_status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Rejected", "REJECTED"),
                ],
                default="Pending",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verification_status__in", ["Pending", "Approved", "Rejected"])
                ),
                name="accounts_BankAccount_verification_status_VerificationStatus",
            ),
        ),
    ]
