# Generated by Django 5.2.15 on 2026-09-24 03:30

import crowdfunding.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0015_remove_bankaccount_accounts_bankaccount_verification_status_verificationstatus_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="branch_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="cancelled_cheque",
            field=models.FileField(
                max_length=500,
                upload_to=crowdfunding.upload_paths.cancelled_cheque_upload_path,
            ),
        ),
    ]
