# Generated by Django 5.2.15 on 2026-07-29 13:38

import crowdfunding.utils
import django.db.models.deletion
import django_enum.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "donation_type",
                    django_enum.fields.EnumCharField(
                        choices=[("Campaign", "CAMPAIGN"), ("Platform", "PLATFORM")],
                        default="Campaign",
                        max_length=8,
                    ),
                ),
                (
                    "unique_donation_number",
                    models.CharField(
                        db_index=True,
                        default=crowdfunding.utils.generate_donation_number,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("INR", "INR"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[("Success", "SUCCESS"), ("Refunded", "REFUNDED")],
                        default="Success",
                        max_length=8,
                    ),
                ),
                ("donated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "donation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationReceipt",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receipt_num",
                    models.CharField(
                        db_index=True,
                        default=crowdfunding.utils.generate_receipt_number,
                        editable=False,
                        max_length=17,
                        unique=True,
                    ),
                ),
                (
                    "receipt_url",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/receipt/%Y/%m/"
                    ),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="donations.donation",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "donation_receipt",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                condition=models.Q(("donation_type__in", ["Campaign", "Platform"])),
                name="donations_Donation_donation_type_DonationType",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ["INR", "USD", "EUR", "GBP"])),
                name="donations_Donation_currency_Currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["Success", "Refunded"])),
                name="donations_Donation_status_DonationStatus",
            ),
        ),
    ]
