# Generated by Django 5.2.15 on 2026-08-06 14:03

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_remove_campaign_available_wallet_balance"),
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="donation",
            name="donations_Donation_status_DonationStatus",
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Success", "SUCCESS"),
                    ("Failed", "FAILED"),
                    ("Refunded", "REFUNDED"),
                ],
                default="Success",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["Pending", "Success", "Failed", "Refunded"])
                ),
                name="donations_Donation_status_DonationStatus",
            ),
        ),
    ]
