# Generated by Django 5.2.15 on 2026-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donations",
            "0002_remove_donation_donations_donation_status_donationstatus_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="donationreceipt",
            name="receipt_file",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/receipt/%Y/%m/"
            ),
        ),
    ]
