# Generated by Django 5.2.15 on 2026-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_donationreceipt_receipt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationreceipt",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
