# Generated by Django 5.2.15 on 2026-08-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_alter_donationreceipt_generated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationreceipt",
            name="receipt_url",
        ),
    ]
