# Generated by Django 5.2.15 on 2026-08-16 15:47

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_remove_donationreceipt_receipt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Success", "SUCCESS"),
                    ("Failed", "FAILED"),
                    ("Refunded", "REFUNDED"),
                ],
                default="Pending",
                max_length=8,
            ),
        ),
    ]
