# Generated by Django 5.2.15 on 2026-08-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0006_alter_donation_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
            },
        ),
        migrations.AlterModelOptions(
            name="donationreceipt",
            options={
                "ordering": ["-generated_at"],
                "verbose_name": "Donation Receipt",
                "verbose_name_plural": "Donation Receipts",
            },
        ),
    ]
