# Generated by Django 5.2.15 on 2026-08-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0033_rename_promotionservicepricing_campaignpromotionservicetypes_and_more",
        ),
        ("donations", "0007_alter_donation_options_alter_donationreceipt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="campaigns.campaign",
            ),
        ),
    ]
