# Generated by Django 5.2.15 on 2026-08-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0008_alter_donation_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="donation",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
