# Generated by Django 5.2.15 on 2026-08-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0009_donation_fee_donation_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="tax",
        ),
    ]
