# Generated by Django 5.2.15 on 2026-08-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0010_remove_donation_fee_remove_donation_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationreceipt",
            name="generated_by",
        ),
    ]
