# Generated by Django 5.2.15 on 2026-08-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0011_remove_donationreceipt_generated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationreceipt",
            name="email_sent_at",
        ),
    ]
