# Generated by Django 5.2.15 on 2026-09-08 06:43

import crowdfunding.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0012_remove_donationreceipt_email_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationreceipt",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=crowdfunding.upload_paths.receipt_upload_path,
            ),
        ),
    ]
