# Generated by Django 5.2.15 on 2026-09-08 12:11

import crowdfunding.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0013_alter_donationreceipt_receipt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationreceipt",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=crowdfunding.upload_paths.receipt_upload_path,
            ),
        ),
    ]
