# Generated by Django 5.2.15 on 2026-09-08 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0035_alter_campaign_beneficiary_mobile"),
        ("donations", "0014_alter_donationreceipt_receipt_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donations",
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
