# Generated by Django 5.2.15 on 2026-08-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
            },
        ),
        migrations.AlterModelTable(
            name="wallet",
            table="wallet",
        ),
        migrations.AlterModelTable(
            name="wallettransaction",
            table="wallet_transaction",
        ),
    ]
