# Generated by Django 5.2.15 on 2026-09-08 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0015_alter_donation_campaign_alter_donation_donor"),
        (
            "payments",
            "0009_remove_paymenttransaction_campaign_promotion_services_and_more",
        ),
        (
            "wallets",
            "0002_alter_wallet_options_alter_wallettransaction_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallettransaction",
            name="campaign_service",
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_wallet_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="donation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_transactions",
                to="donations.donation",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="wallets.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="withdrawal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_transactions",
                to="payments.withdrawal",
            ),
        ),
    ]
