# Generated by Django 5.2.15 on 2026-09-23 09:23

import crowdfunding.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0041_alter_campaign_beneficiary_age"),
        ("wallets", "0003_remove_wallettransaction_campaign_service_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("wallet_type", crowdfunding.enums.WalletType["PLATFORM"])
                ),
                fields=("wallet_type",),
                name="only_one_platform_wallet",
            ),
        ),
    ]
