# Generated by Django 5.2.15 on 2026-07-29 13:38

import django.db.models.deletion
import django_enum.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_type",
                    django_enum.fields.EnumCharField(
                        choices=[("Crowdfunding", "CROWDFUNDING"), ("CSR", "CSR")],
                        default="Crowdfunding",
                        max_length=12,
                    ),
                ),
                ("campaign_name", models.CharField(max_length=255)),
                ("campaign_slug", models.SlugField(max_length=300, unique=True)),
                ("campaign_desc", models.TextField()),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaigns/covers/"
                    ),
                ),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "amount_withdrawn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "available_wallet_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "beneficiary_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Me", "ME"),
                            ("Relative", "RELATIVE"),
                            ("Friend", "FRIEND"),
                            ("Others", "OTHERS"),
                            ("NGO", "NGO"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "beneficiary_group_type",
                    django_enum.fields.EnumCharField(
                        choices=[("Individual", "INDIVIDUAL"), ("Group", "GROUP")],
                        max_length=10,
                    ),
                ),
                (
                    "cause",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Medical", "MEDICAL"),
                            ("Education", "EDUCATION"),
                            ("Memorial", "MEMORIAL"),
                            ("Disaster Relief", "DISASTER_RELIEF"),
                            ("Children", "CHILDREN"),
                            ("Animal Welfare", "ANIMAL_WELFARE"),
                            ("Environment", "ENVIRONMENT"),
                            ("Women Empowerment", "WOMEN_EMPOWERMENT"),
                            ("Community Development", "COMMUNITY_DEVELOPMENT"),
                            (
                                "Livelihood Skill Development",
                                "LIVELIHOOD_SKILL_DEVELOPMENT",
                            ),
                            ("Healthcare", "HEALTHCARE"),
                            ("Others", "OTHERS"),
                        ],
                        max_length=28,
                    ),
                ),
                (
                    "beneficiary_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "beneficiary_relation",
                    django_enum.fields.EnumCharField(
                        blank=True,
                        choices=[
                            ("Mother", "MOTHER"),
                            ("Father", "FATHER"),
                            ("Brother", "BROTHER"),
                            ("Sister", "SISTER"),
                            ("Spouse", "SPOUSE"),
                            ("Child", "CHILD"),
                            ("Others", "OTHERS"),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "beneficiary_mobile",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "beneficiary_member_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "beneficiary_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("beneficiary_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "hospital_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hospital_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ailment", models.TextField(blank=True, null=True)),
                (
                    "campaign_status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Draft", "DRAFT"),
                            ("Pending", "PENDING"),
                            ("Active", "ACTIVE"),
                            ("Paused", "PAUSED"),
                            ("Completed", "COMPLETED"),
                            ("Rejected", "REJECTED"),
                            ("Closed", "CLOSED"),
                        ],
                        default="Draft",
                        max_length=9,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("total_donors", models.PositiveIntegerField(default=0)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ngo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="organizations.ngoprofile",
                    ),
                ),
            ],
            options={
                "db_table": "campaign",
            },
        ),
        migrations.CreateModel(
            name="CampaignPromotionService",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Featured", "FEATURED"),
                            ("Google Ads", "GOOGLE_ADS"),
                            ("Social Media", "SOCIAL_MEDIA"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "promotion_status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Active", "ACTIVE"),
                            ("Completed", "COMPLETED"),
                            ("Cancelled", "CANCELLED"),
                        ],
                        default="Pending",
                        max_length=9,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("campaign_type__in", ["Crowdfunding", "CSR"])),
                name="campaigns_Campaign_campaign_type_CampaignType",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "beneficiary_type__in",
                        ["Me", "Relative", "Friend", "Others", "NGO"],
                    )
                ),
                name="campaigns_Campaign_beneficiary_type_BeneficiaryType",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("beneficiary_group_type__in", ["Individual", "Group"])
                ),
                name="campaigns_Campaign_beneficiary_group_type_BeneficiaryGroupType",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "cause__in",
                        [
                            "Medical",
                            "Education",
                            "Memorial",
                            "Disaster Relief",
                            "Children",
                            "Animal Welfare",
                            "Environment",
                            "Women Empowerment",
                            "Community Development",
                            "Livelihood Skill Development",
                            "Healthcare",
                            "Others",
                        ],
                    )
                ),
                name="campaigns_Campaign_cause_CampaignCause",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "beneficiary_relation__in",
                        [
                            "Mother",
                            "Father",
                            "Brother",
                            "Sister",
                            "Spouse",
                            "Child",
                            "Others",
                        ],
                    ),
                    ("beneficiary_relation__isnull", True),
                    _connector="OR",
                ),
                name="campaigns_Campaign_beneficiary_relation_BeneficiaryRelation",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "campaign_status__in",
                        [
                            "Draft",
                            "Pending",
                            "Active",
                            "Paused",
                            "Completed",
                            "Rejected",
                            "Closed",
                        ],
                    )
                ),
                name="campaigns_Campaign_campaign_status_CampaignStatus",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignpromotionservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_type__in", ["Featured", "Google Ads", "Social Media"])
                ),
                name="campaigns_CampaignPromotionService_service_type_ServiceType",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignpromotionservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "promotion_status__in",
                        ["Pending", "Active", "Completed", "Cancelled"],
                    )
                ),
                name="paigns_CampaignPromotionService_promotion_status_PromotionStatus",
            ),
        ),
    ]
