# Generated by Django 5.2.15 on 2026-08-01 03:09

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0002_remove_campaign_campaigns_campaign_campaign_status_campaignstatus_and_more",
        ),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campaign",
            name="campaigns_Campaign_campaign_status_CampaignStatus",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Draft", "DRAFT"),
                    ("Pending", "PENDING"),
                    ("Active", "ACTIVE"),
                    ("Paused", "PAUSED"),
                    ("Completed", "COMPLETED"),
                    ("Rejected", "REJECTED"),
                    ("Closed", "CLOSED"),
                ],
                default="Draft",
                max_length=9,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "campaign_status__in",
                        [
                            "Draft",
                            "Pending",
                            "Active",
                            "Paused",
                            "Completed",
                            "Rejected",
                            "Closed",
                        ],
                    )
                ),
                name="campaigns_Campaign_campaign_status_CampaignStatus",
            ),
        ),
    ]
