# Generated by Django 5.2.15 on 2026-08-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0003_remove_campaign_campaigns_campaign_campaign_status_campaignstatus_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
