# Generated by Django 5.2.15 on 2026-08-03 14:48

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaign_is_deleted"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campaign",
            name="campaigns_Campaign_beneficiary_type_BeneficiaryType",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="beneficiary_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Me", "ME"),
                    ("Relative", "RELATIVE"),
                    ("Friend", "FRIEND"),
                    ("Others", "OTHERS"),
                    ("NGO", "NGO"),
                    ("Individual", "INDIVIDUAL"),
                    ("Institution", "INSTITUTION"),
                    ("Community", "COMMUNITY"),
                ],
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "beneficiary_type__in",
                        [
                            "Me",
                            "Relative",
                            "Friend",
                            "Others",
                            "NGO",
                            "Individual",
                            "Institution",
                            "Community",
                        ],
                    )
                ),
                name="campaigns_Campaign_beneficiary_type_BeneficiaryType",
            ),
        ),
    ]
