# Generated by Django 5.2.15 on 2026-08-04 08:22

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0006_remove_campaign_campaigns_campaign_beneficiary_group_type_beneficiarygrouptype_and_more",
        ),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campaign",
            name="campaigns_Campaign_beneficiary_group_type_BeneficiaryGroupType",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="beneficiary_group_type",
            field=django_enum.fields.EnumCharField(
                choices=[("Individual", "INDIVIDUAL"), ("Group", "GROUP")],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("beneficiary_group_type__in", ["Individual", "Group"])
                ),
                name="campaigns_Campaign_beneficiary_group_type_BeneficiaryGroupType",
            ),
        ),
    ]
