# Generated by Django 5.2.15 on 2026-08-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0007_remove_campaign_campaigns_campaign_beneficiary_group_type_beneficiarygrouptype_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="available_wallet_balance",
        ),
    ]
