# Generated by Django 5.2.15 on 2026-08-23 13:43

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_remove_campaign_available_wallet_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionServicePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("Featured", "FEATURED"),
                            ("Google Ads", "GOOGLE_ADS"),
                            ("Social Media", "SOCIAL_MEDIA"),
                        ],
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="campaignpromotionservice",
            name="currency",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("INR", "INR"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignpromotionservice",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ["INR", "USD", "EUR", "GBP"])),
                name="campaigns_CampaignPromotionService_currency_Currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionservicepricing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_type__in", ["Featured", "Google Ads", "Social Media"])
                ),
                name="campaigns_PromotionServicePricing_service_type_ServiceType",
            ),
        ),
    ]
