# Generated by Django 5.2.15 on 2026-08-23 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_promotionservicepricing_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campaignpromotionservice",
            name="campaigns_CampaignPromotionService_service_type_ServiceType",
        ),
        migrations.AlterField(
            model_name="campaignpromotionservice",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_promotions",
                to="campaigns.promotionservicepricing",
            ),
        ),
    ]
