# Generated by Django 5.2.15 on 2026-08-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0010_remove_campaignpromotionservice_campaigns_campaignpromotionservice_service_type_servicetype_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="promotionservicepricing",
            table="campaign_promotion_services",
        ),
    ]
