# Generated by Django 5.2.15 on 2026-08-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_alter_promotionservicepricing_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignpromotionservice",
            name="service_type",
        ),
        migrations.DeleteModel(
            name="PromotionServicePricing",
        ),
    ]
