# Generated by Django 5.2.15 on 2026-08-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_alter_promotionservicepricing_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="promotionservicepricing",
            table="campaign_promotion_services_pricing",
        ),
    ]
