# Generated by Django 5.2.15 on 2026-08-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0016_alter_promotionservicepricing_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="campaignpromotionservice",
            table="campaign_promotion_services",
        ),
    ]
