# Generated by Django 5.2.15 on 2026-08-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0017_alter_campaignpromotionservice_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpromotionservice",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_promotions",
                to="campaigns.promotionservicepricing",
            ),
        ),
    ]
