# Generated by Django 5.2.15 on 2026-08-23 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0019_alter_campaignpromotionservice_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionservicepricing",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
