# Generated by Django 5.2.15 on 2026-08-23 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0020_promotionservicepricing_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionservicepricing",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
