# Generated by Django 5.2.15 on 2026-08-23 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0021_alter_promotionservicepricing_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotionservicepricing",
            name="id",
        ),
        migrations.AlterField(
            model_name="promotionservicepricing",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
