# Generated by Django 5.2.15 on 2026-08-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0022_remove_promotionservicepricing_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignpromotionservice",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="campaignpromotionservice",
            name="start_date",
        ),
    ]
