# Generated by Django 5.2.15 on 2026-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0023_remove_campaignpromotionservice_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpromotionservice",
            name="user_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
