# Generated by Django 5.2.15 on 2026-08-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0024_campaignpromotionservice_user_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignpromotionservice",
            name="service_type",
        ),
    ]
