# Generated by Django 5.2.15 on 2026-08-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0025_remove_campaignpromotionservice_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpromotionservice",
            name="service_type",
            field=models.ForeignKey(
                default="706deb9b-faff-4478-a200-bc7753c2d522",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_promotions",
                to="campaigns.promotionservicepricing",
            ),
        ),
    ]
