# Generated by Django 5.2.15 on 2026-08-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0027_alter_campaignpromotionservice_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpromotionservice",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="campaignpromotionservice",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
