# Generated by Django 5.2.15 on 2026-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0028_campaignpromotionservice_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignpromotionservice",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="campaignpromotionservice",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
