# Generated by Django 5.2.15 on 2026-08-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0029_alter_campaignpromotionservice_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="is_featured",
        ),
    ]
