# Generated by Django 5.2.15 on 2026-08-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0030_remove_campaign_is_featured"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="promotionservicepricing",
            name="campaigns_PromotionServicePricing_service_type_ServiceType",
        ),
        migrations.AlterField(
            model_name="promotionservicepricing",
            name="service_type",
            field=models.CharField(default="Google ADS", max_length=50),
        ),
    ]
