# Generated by Django 5.2.15 on 2026-08-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0031_remove_promotionservicepricing_campaigns_promotionservicepricing_service_type_servicetype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionservicepricing",
            name="service_type",
            field=models.CharField(max_length=50),
        ),
    ]
