# Generated by Django 5.2.15 on 2026-08-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0032_alter_promotionservicepricing_service_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PromotionServicePricing",
            new_name="CampaignPromotionServiceTypes",
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={"verbose_name": "Campaign", "verbose_name_plural": "Campaigns"},
        ),
        migrations.AlterModelOptions(
            name="campaignpromotionservice",
            options={
                "verbose_name": "Campaign Promotion Service",
                "verbose_name_plural": "Campaign Promotion Services",
            },
        ),
        migrations.AlterModelOptions(
            name="campaignpromotionservicetypes",
            options={
                "verbose_name": "Campaign Promotion Services Type",
                "verbose_name_plural": "Campaign Promotion Services Types",
            },
        ),
        migrations.RenameField(
            model_name="campaignpromotionservicetypes",
            old_name="service_type",
            new_name="service_name",
        ),
        migrations.AlterModelTable(
            name="campaignpromotionservice",
            table="campaign_promotion_service",
        ),
        migrations.AlterModelTable(
            name="campaignpromotionservicetypes",
            table="campaign_promotion_services_type",
        ),
    ]
