# Generated by Django 5.2.15 on 2026-08-25 05:41

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0033_rename_promotionservicepricing_campaignpromotionservicetypes_and_more",
        ),
        ("organizations", "0002_alter_csrprofile_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campaign",
            name="campaigns_Campaign_beneficiary_relation_BeneficiaryRelation",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="beneficiary_relation",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("Self", "SELF"),
                    ("Mother", "MOTHER"),
                    ("Father", "FATHER"),
                    ("Brother", "BROTHER"),
                    ("Sister", "SISTER"),
                    ("Spouse", "SPOUSE"),
                    ("Child", "CHILD"),
                    ("Others", "OTHERS"),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "beneficiary_relation__in",
                        [
                            "Self",
                            "Mother",
                            "Father",
                            "Brother",
                            "Sister",
                            "Spouse",
                            "Child",
                            "Others",
                        ],
                    ),
                    ("beneficiary_relation__isnull", True),
                    _connector="OR",
                ),
                name="campaigns_Campaign_beneficiary_relation_BeneficiaryRelation",
            ),
        ),
    ]
