# Generated by Django 5.2.15 on 2026-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0034_remove_campaign_campaigns_campaign_beneficiary_relation_beneficiaryrelation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="beneficiary_mobile",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
