# Generated by Django 5.2.15 on 2026-09-09 13:02

import crowdfunding.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0036_alter_campaign_created_by_alter_campaign_ngo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=crowdfunding.upload_paths.campaign_profile_upload_path,
            ),
        ),
    ]
