# Generated by Django 5.2.15 on 2026-09-14 12:54

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0037_alter_campaign_cover_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignpromotionservice",
            name="service_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Social Media", "SOCIAL_MEDIA"),
                    ("Featured", "FEATURED"),
                    ("Google Ads", "GOOGLE_ADS"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignpromotionservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_type__in", ["Social Media", "Featured", "Google Ads"])
                ),
                name="mpaignPromotionService_service_type_CampaignPromotionServiceType",
            ),
        ),
        migrations.DeleteModel(
            name="CampaignPromotionServiceTypes",
        ),
    ]
