# Generated by Django 5.2.15 on 2026-09-15 14:49

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0038_alter_campaignpromotionservice_service_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campaignpromotionservice",
            name="paigns_CampaignPromotionService_promotion_status_PromotionStatus",
        ),
        migrations.AlterField(
            model_name="campaignpromotionservice",
            name="promotion_status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Submitted", "SUBMITTED"),
                    ("Active", "ACTIVE"),
                    ("Completed", "COMPLETED"),
                    ("Cancelled", "CANCELLED"),
                ],
                default="Pending",
                max_length=9,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignpromotionservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "promotion_status__in",
                        ["Pending", "Submitted", "Active", "Completed", "Cancelled"],
                    )
                ),
                name="paigns_CampaignPromotionService_promotion_status_PromotionStatus",
            ),
        ),
    ]
