# Generated by Django 5.2.15 on 2026-09-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0039_remove_campaignpromotionservice_paigns_campaignpromotionservice_promotion_status_promotionstatus_and",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="total_charges",
        ),
    ]
