# Generated by Django 5.2.15 on 2026-09-23 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0040_remove_campaign_total_charges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="beneficiary_age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(122)],
            ),
        ),
    ]
